<div class="field neighborhood">
    <label class="label" for="neighborhood"><span><?php /* @escapeNotVerified */ echo __('Neighborhood') ?></span></label>
    <div class="control">
        <input type="text" name="neighborhood" value="<?php echo $block->getneighborhoodValue() ?>" title="<?php /* @escapeNotVerified */ echo __('Neighborhood') ?>" id="neighborhood" class="input-text" >
    </div>
</div>